config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users

  resources :boardgroup do
    resources :board do
      resources :task
    end
    
    resources :team
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :tasks, dependent: :destroy
  belongs_to :boardgroup

  validates :title, presence: true, length: { maximum: 50 } 
  validates :boardgroup_id, presence: true, numericality: true
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  before_action :authenticate_user!

  def show
    @todo_tasks = Task.where("(board_id = ?) AND (status_id = ?)", params[:id], 1)
    @do_tasks = Task.where("(board_id = ?) AND (status_id = ?)", params[:id], 2)
    @finish_tasks = Task.where("(board_id = ?) AND (status_id = ?)", params[:id], 3)
  end

  def new
    @board = Board.new
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boardgroup_url(@board.boardgroup_id), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :new
    end
  end

  def edit
    @board = Board.find(params[:id])
  end

  def update
    @board = Board.find(params[:id])
    if @board.update(board_params)
      redirect_to boardgroup_url(params[:boardgroup_id]), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :edit
    end
  end

  def destroy
    @board = Board.find(params[:id])
    if @board.destroy
      redirect_to boardgroup_url(params[:boardgroup_id]), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :show
    end
  end

  private

  def board_params
    params.require(:board).permit(:title, :boardgroup_id)
  end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/views/board/_form.html.erb
<div class="text-center lg:w-3/4 m-auto">
  <div>ボードのタイトル</div>
  <div><%= form.text_field :title, placeholder: "タイトルを入力してください" %></div>
  <div><%= form.hidden_field :boardgroup_id, value: params[:boardgroup_id] %></div>
  <div><%= form.submit '送信', class: "w-full border-none rounded bg-gray-800 text-white p-1 my-2" %></div>
</div>

app/views/board/edit.html.erb
<div class="background-base p-5">
  <div class="rounded-xl bg-gray-200 shadow-lg lg:w-1/4 m-auto">
    <div class="rounded bg-gray-600">
      <h2 class="text-white p-1">ボードの編集</h2>
    </div>
    <div class="p-2">
      <%= form_with model: @board, url: boardgroup_board_path(params[:boardgroup_id], params[:id]) do |form| %>
        <%= render :partial => "form", :locals=>{:form => form} %>
      <% end %>
    </div>
  </div>
</div>

app/views/board/new.html.erb
<div class="background-base p-5">
  <div class="rounded-xl bg-gray-200 shadow-lg lg:w-1/4 m-auto">
    <div class="rounded bg-gray-600">
      <h2 class="text-white p-1">新規作成</h2>
    </div>
    <div class="p-2">
      <%= form_with model: @board, url: boardgroup_board_index_path do |form| %>
        <%= render :partial => "form", :locals=>{:form => form} %>
      <% end %>
    </div>
  </div>
</div>

app/views/board/show.html.erb
<div class="background-base p-5">
  <div class="m-auto p-2 lg:w-2/3">
    <h1 class="text-3xl">タスク一覧</h1>
    <div class="block space-y-2 justify-between py-3 lg:flex lg:space-y-0 lg:space-x-1">
      <div class="w-full lg:m-0 my-1"><%= link_to 'タスク作成', new_boardgroup_board_task_path(params[:boardgroup_id], params[:id]), class: "block btn-base" %></div>
      <div class="w-full lg:m-0 my-1"><%= link_to 'ボード編集', edit_boardgroup_board_path(params[:boardgroup_id], params[:id]), class: "block btn-base" %></div>
      <div class="w-full lg:m-0 my-1"><%= link_to 'ボード削除', boardgroup_board_path(params[:boardgroup_id], params[:id]), method: :delete, class: "block btn-base" %></div>
    </div>

    <div class="space-y-4">
      <div>
        <h2 class="text-xl">Todo</h2>
        <% unless @todo_tasks.size == 0 %>
          <% @todo_tasks.each do |task| %>
            <div class="content-box my-2">
              <%= link_to task.title, boardgroup_board_task_path(params[:boardgroup_id], task.board_id, task.id), class: "block w-full underline" %>
              <p>締切:<%= task.dead_line %></p>
            </div>
          <% end %>
        <% else %>
          <div class="content-box">
            <p>タスクがありません</p>
          </div>
        <% end %>
      </div>

      <div>
        <h2 class="text-xl">作業中</h2>
        <% unless @do_tasks.size == 0 %>
          <% @do_tasks.each do |dtask| %>
            <div class="content-box my-2">
              <%= link_to dtask.title, boardgroup_board_task_path(params[:boardgroup_id], dtask.board_id, dtask.id), class: "block w-full underline" %>
              <p>締切:<%= dtask.dead_line %></p>
            </div>
          <% end %>
        <% else %>
          <div class="content-box my-2">
            <p>タスクがありません</p>
          </div>
        <% end %>
      </div>

      <div>
        <h2 class="text-xl">完了</h2>
        <% unless @finish_tasks.size == 0 %>
          <% @finish_tasks.each do |ftask| %>
            <div class="content-box my-2">
              <%= link_to ftask.title, boardgroup_board_task_path(params[:boardgroup_id], ftask.board_id, ftask.id), class: "block w-full underline" %>
              <p>締切:<%= ftask.dead_line %></p>
            </div>
          <% end %>
        <% else %>
          <div class="content-box my-2">
            <p>タスクがありません</p>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>