config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users

  resources :boardgroup do
    resources :board do
      resources :task
    end
    
    resources :team
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :status
  belongs_to :board

  validates :title, presence: true, length: { maximum: 50 }
  validates :status_id, presence: true, numericality: true
  validates :board_id, presence: true, numericality: true
end

app/controllers/task_controller.rb
class TaskController < ApplicationController
  before_action :authenticate_user!

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
    @statuses = Status.all
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to boardgroup_board_url(params[:boardgroup_id], @task.board_id), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
    @statuses = Status.all
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to boardgroup_board_task_url(params[:boardgroup_id], params[:board_id], params[:id]), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    if @task.destroy
      redirect_to boardgroup_board_url(params[:boardgroup_id], params[:board_id]), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :show
    end
  end

  private

  def task_params
    params.require(:task).permit(:title, :detail, :dead_line, :status_id, :board_id)
  end
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/task/_form.html.erb
<div class="text-center lg:w-3/4 m-auto">
  <div class="space-y-2">
    <div>タイトル</div>
    <div><%= form.text_field :title, placeholder: "タイトルを入力してください" %></div>
    <div>詳細</div>
    <div><%= form.text_area :detail, size: "23*10", placeholder: "詳細を入力してください" %></div>
    <div>締切</div>
    <div><%= form.datetime_field :dead_line %></div>
    <div>状態</div>
    <div><%= form.select :status_id, @statuses.map{ |st| [st.status, st.id] } %></div>
    <%= form.hidden_field :board_id, value: params[:board_id] %>
    <div><%= form.submit '作成', class: "btn-base" %></div>
  </div>
</div>

app/views/task/edit.html.erb
<div class="background-base p-5">
  <div class="rounded-xl bg-gray-200 shadow-lg lg:w-1/4 m-auto">
    <div class="rounded bg-gray-600">
      <h2 class="text-white p-1">タスクの編集</h2>
    </div>
    <div class="p-2">
      <%= form_with model: @task, url: boardgroup_board_task_path(params[:boardgroup_id], params[:board_id], params[:id]) do |form| %>
        <%= render :partial => "form", :locals=>{:form => form} %>
      <% end %>
    </div>
  </div>
</div>

app/views/task/new.html.erb
<div class="background-base p-5">
  <div class="rounded-xl bg-gray-200 shadow-lg lg:w-1/4 m-auto">
    <div class="rounded bg-gray-600">
      <h2 class="text-white p-1">タスク新規作成</h2>
    </div>
    <div class="p-2">
      <%= form_with model: @task, url: boardgroup_board_task_index_path do |form| %>
        <%= render :partial => "form", :locals=>{:form => form} %>
      <% end %>
    </div>
  </div>
</div>

app/views/task/show.html.erb
<div class="background-base p-5">
  <div class="m-auto p-2 lg:w-2/3">
    <div class="block lg:flex justify-end lg:space-x-2 p-1">
      <div><%= link_to 'タスク編集', edit_boardgroup_board_task_path(params[:boardgroup_id], params[:board_id], params[:id]), class: "block btn-base" %></div>
      <div><%= link_to 'タスク削除', boardgroup_board_task_path(params[:boardgroup_id], params[:board_id], params[:id]), method: :delete, class: "block btn-base" %></div>
    </div>
    <div class="space-y-4">
      <h2 class="text-3xl"><%= @task.title %></h2>
      <div class="rounded-xl text-left bg-gray-200 shadow-lg">
        <div class="rounded border-b-1 bg-gray-600 p-1 shadow-md"><p class="text-white">詳細</p></div>
        <div class="h-auto p-1 prose">
          <%= markdown(@task.detail) %>
        </div>
        <div class="bg-gray-600 p-1 shadow-md"><p class="text-white">締切</p></div>
        <div class="h-auto p-1">
          <%= @task.dead_line %>
        </div>
        <div class="bg-gray-600 p-1 shadow-md"><p class="text-white">作成日時</p></div>
        <div class="h-auto p-1"><%= @task.created_at %></div>
        <div class="bg-gray-600 p-1 shadow-md"><p class="text-white">更新日時</p></div>
        <div class="p-1">
          <%= @task.updated_at %>
        </div>
      </div>
    </div>
  </div>
</div>