config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users

  resources :boardgroup do
    resources :board do
      resources :task
    end
    
    resources :team
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="bg-gray-800 p-1 min-h-[2rem]">
  <div class="text-center">
    <small class="text-white">&copy;kaito071831 2022</small>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="h-[5rem] fixed w-full">
  <nav class="p-4 bg-teal-900">
    <div class="block lg:flex justify-between text-center text-white">
      <div><%= link_to 'TaskControl', root_path, class: "text-3xl" %></div>
      <div class="hidden space-y-2 lg:flex lg:items-center lg:space-x-2 lg:space-y-0">
        <% if user_signed_in? %>
          <div>ID: <%= current_user.id %> <%= link_to current_user.email, boardgroup_index_path, class: "underline" %></div>
          <div><%= link_to 'プロフィール変更', edit_user_registration_path, class: "block border-solid border-2 border-green-600 bg-green-400 px-4 py-2 rounded-full w-full" %></div>
          <div><%= button_to 'ログアウト', destroy_user_session_path, class: "block border-solid border-2 border-green-600 bg-green-400 px-4 py-2 rounded-full w-full cursor-pointer", method: :delete %></div>
        <% else %>
          <div><%= link_to 'サインアップ', new_user_registration_path, class: "block border-solid border-2 border-green-600 bg-green-400 px-4 py-2 rounded-full w-full" %></div>
          <div><%= link_to 'ログイン', new_user_session_path, class: "block border-solid border-2 border-green-600 bg-green-400 px-4 py-2 rounded-full w-full" %></div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_navigation.html.erb
<div id="toggle" class="lg:hidden">
  <div id="toggle-box">
    <span></span>
    <span></span>
    <span></span>
  </div>
</div>

<div id="nav-content" class="pt-5">
  <nav>
    <ul>
      <% if user_signed_in? %>
        <li>ID: <%= current_user.id %><%= link_to current_user.email, boardgroup_index_path %></li>
        <% case controller_name %>
        <% when "boardgroup" %>
          <li><%= link_to 'グループ新規作成', new_boardgroup_path %></li>
          <% if %w(show edit).any?(action_name) %>
            <li><%= link_to 'ボード作成', new_boardgroup_board_path(params[:id]) %></li>
            <li><%= link_to 'グループ編集', edit_boardgroup_path(params[:id]) %></li>
            <li><%= link_to 'グループ削除', boardgroup_path(params[:id]), method: :delete %></li>
            <li><%= link_to '共有設定', boardgroup_team_index_path(params[:id]) %></li>
          <% end %>
        <% when "board" %>
          <% if %w(show edit).any?(action_name) %>
            <li><%= link_to 'タスク作成', new_boardgroup_board_task_path(params[:boardgroup_id], params[:id]) %></li>
            <li><%= link_to 'ボード編集', edit_boardgroup_board_path(params[:boardgroup_id], params[:id]) %></li>
            <li><%= link_to 'ボード削除', boardgroup_board_path(params[:boardgroup_id], params[:id]), method: :delete %></li>
          <% end %>
        <% when "task" %>
          <% if %w(show edit).any?(action_name) %>
            <li><%= link_to 'タスク編集', edit_boardgroup_board_task_path(params[:boardgroup_id], params[:board_id], params[:id]) %></li>
            <li><%= link_to 'タスク削除', boardgroup_board_task_path(params[:boardgroup_id], params[:board_id], params[:id]), method: :delete %></li>
          <% end %>
        <% when "team" %>
          <% if %w(index new).any?(action_name) %>
            <li><%= link_to '共有者追加', new_boardgroup_team_path(params[:boardgroup_id]) %></li>
          <% end %>
        <% end %>
        <li><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
        <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to '戻る', :back %></li>
      <% else %>
        <li><%= link_to 'サインアップ', new_user_registration_path %></li>
        <li><%= link_to 'ログイン', new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</div>