config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  devise_for :users

  resources :boardgroup do
    resources :board do
      resources :task
    end
    
    resources :team
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :user
  belongs_to :boardgroup

  validates :user_id, presence: true, numericality: true
  validates :boardgroup_id, presence: true, numericality: true
end

app/controllers/team_controller.rb
class TeamController < ApplicationController
  before_action :authenticate_user!

  def index
    @board = Boardgroup.find(params[:boardgroup_id])
    @team = current_user.teams.find_by(boardgroup: @board)
  end

  def new
    @team = Team.new
  end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to boardgroup_url(params[:boardgroup_id]), notice: "Success"
    else
      flash.now[:alert] = "Failed"
      render :new
    end
  end

  def destroy
    @team = Team.find(params[:id])
    @other_users = Team.where(boardgroup_id: @team.boardgroup_id).count.to_i
    if @other_users > 1
      if @team.destroy
        redirect_to boardgroup_index_url, notice: "Success"
      else
        redirect_to boardgroup_team_url(params[:boardgroup_id], params[:id]), notice: "Failed"
      end
    else
      redirect_to boardgroup_team_index_url(params[:boardgroup_id]), notice: "Make sure that there are at least two users who can see the board."
    end
  end

  private

  def team_params
    params.require(:team).permit(:user_id, :boardgroup_id)
  end

end

app/helpers/team_helper.rb
module TeamHelper
end

app/views/team/index.html.erb
<div class="background-base p-5">
  <div class="rounded-xl bg-gray-200 shadow-lg lg:w-1/4 m-auto">
    <div class="rounded bg-gray-600">
      <h2 class="text-white p-1">共有者編集</h2>
    </div>
    <div class="p-2">
      <div><%= link_to '共有者追加', new_boardgroup_team_path(params[:boardgroup_id]), class: "block btn-base" %></div>
      <div><%= button_to 'グループから抜ける', boardgroup_team_path(params[:boardgroup_id], @team.id), method: :delete, class: "btn-base" %></div>
      <div>
        <div>所属しているユーザー</div>
        <% @board.users.each do |user| %>
          <p>ID:<%= user.id%> <%= user.email %></p>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/team/new.html.erb
<div class="background-base p-5">
  <div class="rounded-xl bg-gray-200 shadow-lg lg:w-1/4 m-auto">
    <div class="rounded bg-gray-600">
      <h2 class="text-white p-1">共有設定</h2>
    </div>
    <div class="p-2">
      <%= form_with model: @team, url: boardgroup_team_index_path do |form| %>
        <div class="text-center lg:w-3/4 m-auto">
          <div>共有したいユーザーID</div>
          <div><%= form.text_field :user_id, placeholder: "共有したいユーザーのID" %></div>
          <%= form.hidden_field :boardgroup_id, value: params[:boardgroup_id] %>
          <div><%= form.submit '作成', class: "btn-base" %></div>
        </div>
      <% end %>
    </div>
  </div>
</div>